apiVersion: batch/v1
kind: Job
metadata:
  name: solving-pypsa-$ITEM
  # name: solving-pypsa
  namespace: bucket-fuse
  labels:
    jobgroup: prepared-solver
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: solver-pod
      namespace: bucket-fuse
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        jobgroup: prepared-solver
    spec:
      serviceAccountName: bucket-account
      restartPolicy: Never
      containers:
        - name: sol-img
          image: akshatmittaloet/demo-pypsa:sol
          volumeMounts:
            - name: gcs-fuse-csi-inline-1
              mountPath: "/prepared_networks"
            - name: gcs-fuse-csi-inline-2
              mountPath: "/solved_networks"
      volumes:
      - name: gcs-fuse-csi-inline-1
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            # bucketName: cal-cluster-input
            bucketName: bucket-$ITEM-volume
            mountOptions: "debug_fuse,debug_fs,debug_gcs,implicit-dirs,only-dir=prepared_networks"
      - name: gcs-fuse-csi-inline-2
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            # bucketName: cal-cluster-input
            bucketName: bucket-$ITEM-volume
            mountOptions: "debug_fuse,debug_fs,debug_gcs,implicit-dirs,only-dir=solved_networks"