apiVersion: v1
kind: Pod
metadata:
  name: gcs-fuse-csi-example-static-pvc
  namespace: bucket-fuse
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  containers:
  - image: akshatmittaloet/demo-pypsa:cal
    name: cal-img
    volumeMounts:
    - name: gcs-fuse-csi-static
      mountPath: /input
      readOnly: false
  serviceAccountName: bucket-account
  volumes:
  - name: gcs-fuse-csi-static
    persistentVolumeClaim:
      claimName: gcs-fuse-csi-static-pvc