apiVersion: v1
kind: Pod
metadata:
  name: gcs-fuse-csi-example-static-pvc
  namespace: bucket-fuse
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  serviceAccountName: bucket-account
  restartPolicy: Never
  containers:
    - name: cal-img
      image: akshatmittaloet/demo-pypsa:cal
      volumeMounts:
        - name: gcs-fuse-csi-inline-1
          mountPath: "/input"
        - name: gcs-fuse-csi-inline-2
          mountPath: "/results"
  volumes:
  - name: gcs-fuse-csi-inline-1
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: cal-cluster-input
        mountOptions: "debug_fuse,debug_fs,debug_gcs,implicit-dirs,only-dir=input"
  - name: gcs-fuse-csi-inline-2
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: cal-cluster-input
        mountOptions: "debug_fuse,debug_fs,debug_gcs,implicit-dirs,only-dir=results"