apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  storageClassName: example-storage-class
  claimRef:
    namespace: bucket-fuse
    name: gcs-fuse-csi-static-pvc
  mountOptions:
    - implicit-dirs
    - only-dir= input/
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: remotesnake
    readOnly: false
    
